// SPDX-License-Identifier: GPL-3.0-only
/*
 *  Prism Launcher - Minecraft Launcher
 *  Copyright (C) 2025 IAG Engineers
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, version 3.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "HyperMinePage.h"
// Generated by AUTOUIC, which flattens .ui headers to ui_<ClassName>.h regardless of
// which subdirectory the .ui file lives in.
#include "ui_HyperMinePage.h"

#include <QColor>
#include <QDateTime>
#include <QDir>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QHeaderView>
#include <QItemSelectionModel>
#include <QStandardItem>
#include <QStandardItemModel>
#include <QTime>
#include <QTimer>

#include <memory>

#include "Application.h"
#include "FileSystem.h"
#include "InstanceList.h"
#include "minecraft/MinecraftInstance.h"
#include "minecraft/launch/MinecraftTarget.h"
#include "ui/dialogs/CustomMessageBox.h"

namespace {

constexpr const char* kConfPathKey = "HyperMine/ConfPath";
constexpr const char* kPanelUrlKey = "HyperMine/PanelUrl";
constexpr const char* kPanelTokenKey = "HyperMine/PanelToken";
constexpr const char* kPanelPortKey = "HyperMine/PanelPort";
constexpr const char* kAutoTunnelKey = "HyperMine/AutoTunnel";
constexpr const char* kLastInstanceKey = "HyperMine/LastInstance";
constexpr const char* kDefaultMcPortKey = "HyperMine/DefaultMcPort";

/** Port assumed for the panel when nothing else says otherwise. */
constexpr int kDefaultPanelPort = 8080;
/** How long Play waits for a handshake before giving up. */
constexpr int kPlayHandshakeTimeoutMs = 30000;

constexpr int kServerColumnCount = 4;

}  // namespace

HyperMinePage::HyperMinePage(QWidget* parent) : QWidget(parent)
{
    ui = new Ui::HyperMinePage();
    ui->setupUi(this);

    m_tunnel = new WireGuardTunnel(this);
    m_tunnel->setConfigDir(QDir(FS::PathCombine(APPLICATION->dataRoot(), "hypermine", "wireguard")));

    m_client = new HyperMineClient(this);

    m_serverModel = new QStandardItemModel(this);
    m_serverModel->setHorizontalHeaderLabels({ "Name", "State", "Players", "Java" });
    ui->serverView->setModel(m_serverModel);
    ui->serverView->horizontalHeader()->setSectionResizeMode(QHeaderView::ResizeToContents);
    ui->serverView->verticalHeader()->setVisible(false);

    connect(ui->importButton, &QPushButton::clicked, this, &HyperMinePage::onImportClicked);
    connect(ui->forgetButton, &QPushButton::clicked, this, &HyperMinePage::onForgetClicked);
    connect(ui->upButton, &QPushButton::clicked, this, &HyperMinePage::onUpClicked);
    connect(ui->downButton, &QPushButton::clicked, this, &HyperMinePage::onDownClicked);
    connect(ui->savePanelButton, &QPushButton::clicked, this, &HyperMinePage::onSavePanelClicked);
    connect(ui->refreshButton, &QPushButton::clicked, this, &HyperMinePage::onRefreshClicked);
    connect(ui->startButton, &QPushButton::clicked, this, &HyperMinePage::onStartClicked);
    connect(ui->stopButton, &QPushButton::clicked, this, &HyperMinePage::onStopClicked);
    connect(ui->playButton, &QPushButton::clicked, this, &HyperMinePage::onPlayClicked);

    auto* selection = ui->serverView->selectionModel();
    connect(selection, &QItemSelectionModel::selectionChanged, this, &HyperMinePage::onSelectionChanged);
    connect(ui->serverView, &QTableView::doubleClicked, this, &HyperMinePage::onPlayClicked);

    connect(m_tunnel, &WireGuardTunnel::statusChanged, this, &HyperMinePage::onTunnelStatusChanged);
    connect(m_tunnel, &WireGuardTunnel::logMessage, this, &HyperMinePage::onTunnelLog);

    connect(m_client, &HyperMineClient::serversReceived, this, &HyperMinePage::onServersReceived);
    connect(m_client, &HyperMineClient::requestFailed, this, &HyperMinePage::onRequestFailed);
    connect(m_client, &HyperMineClient::actionFinished, this, &HyperMinePage::onActionFinished);
    // Stop the panel buttons firing a second request while one is in flight.
    connect(m_client, &HyperMineClient::busyChanged, this, &HyperMinePage::refreshButtonStates);

    connect(APPLICATION->instances(), &InstanceList::instancesChanged, this, &HyperMinePage::populateInstances);

    // Bounds a Play click on its own clock. It must not be driven by tunnel status
    // changes, because the case that most needs a timeout -- tunnel down, auto-bring-up
    // off -- produces no status change at all.
    m_pendingPlayTimer = new QTimer(this);
    m_pendingPlayTimer->setSingleShot(true);
    m_pendingPlayTimer->setInterval(kPlayHandshakeTimeoutMs);
    connect(m_pendingPlayTimer, &QTimer::timeout, this, &HyperMinePage::onPendingPlayTimeout);

    reload();
}

HyperMinePage::~HyperMinePage()
{
    delete ui;
}

void HyperMinePage::reload()
{
    loadTunnelFromSettings();

    auto* settings = APPLICATION->settings();
    ui->addressEdit->setText(settings->get(kPanelUrlKey).toString());
    ui->tokenEdit->setText(settings->get(kPanelTokenKey).toString());
    // QVariant::toBool() takes no default in Qt 6, so the default lives here. An unset
    // setting comes back as an invalid QVariant, which is what opts for "on".
    const QVariant autoTunnel = settings->get(kAutoTunnelKey);
    ui->autoTunnelCheck->setChecked(autoTunnel.isValid() ? autoTunnel.toBool() : true);

    // An address that was never set by hand follows the tunnel, which is where the panel
    // is expected to be. One that was set by hand is left alone.
    if (ui->addressEdit->text().isEmpty()) {
        const QUrl suggested = suggestedPanelUrl();
        if (suggested.isValid()) {
            ui->addressEdit->setPlaceholderText(suggested.toString());
        }
    }

    populateInstances();
    // Push the loaded address and token into the client straight away. Without this the
    // tab opens showing "no panel address configured" and a disabled Refresh button even
    // though a perfectly good address is saved, until the user presses Save by hand.
    applyPanelSettings();
    refreshTunnelLabels();
    refreshPlayAddress();
}

void HyperMinePage::loadTunnelFromSettings()
{
    const QString confPath = APPLICATION->settings()->get(kConfPathKey).toString();
    if (confPath.isEmpty()) {
        m_tunnel->clearInterface();
        return;
    }

    QFile file(confPath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        // Not fatal: the tab is still usable, it just has no tunnel until one is imported.
        m_tunnel->clearInterface();
        appendLog(tr("Could not reopen %1: %2").arg(confPath, file.errorString()));
        return;
    }
    const QString text = QString::fromUtf8(file.readAll());
    file.close();

    // The interface name comes from the file name, which is what wg-quick and
    // wireguard.exe both use to name the tunnel.
    const QString name = QFileInfo(confPath).completeBaseName();
    QString error;
    const WireGuardInterface iface = WireGuardInterface::fromConf(text, name, &error);
    if (iface.name.isEmpty()) {
        m_tunnel->clearInterface();
        appendLog(tr("Ignoring %1: %2").arg(confPath, error));
        return;
    }
    m_tunnel->setInterface(iface);
    m_tunnel->refresh();
}

void HyperMinePage::saveTunnelToSettings(const QString& confPath)
{
    APPLICATION->settings()->set(kConfPathKey, confPath);
}

void HyperMinePage::activate()
{
    if (ui->autoTunnelCheck->isChecked() && m_tunnel->hasInterface() && !m_tunnel->isUp()) {
        m_tunnel->bringUp();
    }
    if (m_client->canSend()) {
        m_client->fetchServers();
    }
}

void HyperMinePage::onImportClicked()
{
    const QString path = QFileDialog::getOpenFileName(this, tr("Import a WireGuard configuration"), QString(),
                                                      tr("WireGuard configurations (*.conf);;All files (*)"));
    if (path.isEmpty()) {
        return;
    }

    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        CustomMessageBox::selectable(this, tr("Could not read the configuration"),
                                      tr("Could not open %1: %2").arg(path, file.errorString()))
            ->show();
        return;
    }
    const QString text = QString::fromUtf8(file.readAll());
    file.close();

    const QString name = QFileInfo(path).completeBaseName();
    QString error;
    const WireGuardInterface iface = WireGuardInterface::fromConf(text, name, &error);
    if (iface.name.isEmpty()) {
        // The reason is shown rather than swallowed: a config that looks fine but has,
        // say, a truncated key is otherwise a silent no-op.
        CustomMessageBox::selectable(this, tr("That configuration cannot be used"), error)->show();
        return;
    }

    m_tunnel->setInterface(iface);
    // Persist the canonical copy the tunnel actually uses, not the file the user picked.
    // Importing from a USB stick and then re-reading that same stick on next launch would
    // leave the copy under dataRoot orphaned and silently follow the original around.
    saveTunnelToSettings(m_tunnel->confPath());
    appendLog(tr("Imported the %1 tunnel from %2").arg(iface.name, path));

    // A newly imported tunnel usually means a new panel address, so offer the derived one.
    const QUrl suggested = suggestedPanelUrl();
    if (ui->addressEdit->text().isEmpty() && suggested.isValid()) {
        ui->addressEdit->setText(suggested.toString());
        APPLICATION->settings()->set(kPanelUrlKey, suggested.toString());
    }

    refreshTunnelLabels();
    // The derived address above was written to the widget and to settings; push it into
    // the client too, or the panel buttons stay disabled until the user presses Save.
    applyPanelSettings();
    refreshPlayAddress();

    if (ui->autoTunnelCheck->isChecked()) {
        m_tunnel->bringUp();
    }
}

void HyperMinePage::onForgetClicked()
{
    clearPendingPlay();
    // forget() tears the tunnel down before discarding the config. Doing it the other
    // way round here would cancel the uninstall half-way and leave the interface
    // installed with nothing left to manage it.
    m_tunnel->forget();
    APPLICATION->settings()->set(kConfPathKey, QString());
    appendLog(tr("Forgot the imported tunnel."));
    refreshTunnelLabels();
    refreshPanelAvailability();
    refreshPlayAddress();
}

void HyperMinePage::onUpClicked()
{
    clearPendingPlay();
    m_tunnel->bringUp();
}

void HyperMinePage::onDownClicked()
{
    clearPendingPlay();
    m_tunnel->bringDown();
}

void HyperMinePage::onSavePanelClicked()
{
    auto* settings = APPLICATION->settings();
    const QString address = ui->addressEdit->text().trimmed();
    if (!address.isEmpty()) {
        const QUrl url(address);
        if (!url.isValid() || url.host().isEmpty()) {
            CustomMessageBox::selectable(this, tr("That address is not usable"),
                                          tr("'%1' is not a valid URL. It needs to look like http://10.13.0.1:8080.")
                                              .arg(address))
                ->show();
            return;
        }
    }
    settings->set(kPanelUrlKey, address);
    settings->set(kPanelTokenKey, ui->tokenEdit->text());
    settings->set(kAutoTunnelKey, ui->autoTunnelCheck->isChecked());
    applyPanelSettings();
    appendLog(tr("Saved the panel settings."));
}

void HyperMinePage::applyPanelSettings()
{
    const QString address = ui->addressEdit->text().trimmed();
    m_client->setBaseUrl(address.isEmpty() ? QUrl{} : QUrl(address));
    m_client->setToken(ui->tokenEdit->text());
    // isHandshakeFresh, not hasHandshake: a tunnel that handshaked an hour ago and then
    // went stale is exactly the case the client's guard exists to catch, and "has
    // handshaked once" would wave it through.
    m_client->setTunnelUp(m_tunnel->isUp() && m_tunnel->isHandshakeFresh());
    refreshPanelAvailability();
}

void HyperMinePage::onRefreshClicked()
{
    applyPanelSettings();
    m_client->fetchServers();
}

void HyperMinePage::onStartClicked()
{
    const auto server = selectedServer();
    if (!server) {
        return;
    }
    applyPanelSettings();
    m_client->startServer(server->id);
}

void HyperMinePage::onStopClicked()
{
    const auto server = selectedServer();
    if (!server) {
        return;
    }
    applyPanelSettings();
    m_client->stopServer(server->id);
}

void HyperMinePage::onSelectionChanged()
{
    refreshButtonStates();
    refreshPlayAddress();
}

void HyperMinePage::onTunnelStatusChanged()
{
    // The client's idea of whether the link is up has to follow the tunnel's, or
    // canSend() decides on a link state that is minutes out of date.
    const bool linkUp = m_tunnel->isUp() && m_tunnel->isHandshakeFresh();
    if (linkUp != m_client->tunnelUp()) {
        m_client->setTunnelUp(linkUp);
        appendLog(linkUp ? tr("The tunnel handshaked; the panel is reachable again.")
                         : tr("The tunnel is not carrying traffic; the panel is unreachable."));
        // The stale server list is now misleading, so drop it rather than leave rows the
        // user cannot act on.
        if (!linkUp) {
            m_servers.clear();
            populateServers({});
        }
    }

    refreshTunnelLabels();
    refreshPanelAvailability();
    refreshPlayAddress();
    tryCompletePendingPlay();
}

void HyperMinePage::onTunnelLog(const QString& message)
{
    appendLog(message);
}

void HyperMinePage::onServersReceived(const QVector<HyperMineServer>& servers)
{
    m_servers = servers;
    populateServers(servers);
    ui->panelStatusLabel->setText(servers.isEmpty() ? tr("The panel reported no servers.")
                                                    : tr("%n server(s) reported by the panel.", nullptr, servers.size()));
    refreshButtonStates();
    refreshPlayAddress();
}

void HyperMinePage::onRequestFailed(const QString& message)
{
    ui->panelStatusLabel->setText(message);
    appendLog(message);
    refreshPanelAvailability();
}

void HyperMinePage::onActionFinished(const QString& serverId, bool success, const QString& message)
{
    if (success) {
        appendLog(message);
        // The panel's own state is the authority on whether a server is up; asking again
        // is cheaper than guessing from a start request that was merely accepted.
        m_client->fetchServers();
    } else {
        CustomMessageBox::selectable(this, tr("The panel refused the request"), message)->show();
    }
    Q_UNUSED(serverId)
}

void HyperMinePage::populateServers(const QVector<HyperMineServer>& servers)
{
    m_serverModel->removeRows(0, m_serverModel->rowCount());

    for (const auto& server : servers) {
        QString players = QStringLiteral("-");
        if (server.playersMax > 0) {
            players = QStringLiteral("%1 / %2").arg(server.playersOnline).arg(server.playersMax);
        } else if (server.playersOnline > 0) {
            players = QString::number(server.playersOnline);
        }

        // World integrity is intentionally not a column. The failsafe lives in the panel
        // process beside the world it protects; a column here could only ever be a stale
        // copy of what the panel already knows, and it would invite the question of what
        // the client would do about it. The answer is nothing: that is the server's job.
        const QStringList cells = { server.name.isEmpty() ? tr("(unnamed)") : server.name, server.state, players,
                                    server.javaVersion };

        // setItem rather than appendRow: appendRow(item) starts a *new row* for each
        // item, which would give one row per column instead of one row per server.
        const int row = m_serverModel->rowCount();
        for (int column = 0; column < kServerColumnCount; ++column) {
            auto* item = new QStandardItem(cells.at(column));
            item->setEditable(false);
            // The id is what every action is addressed by, so it rides along on the row
            // and is read back by selectedServer().
            if (column == 0) {
                item->setData(server.id, Qt::UserRole);
            }
            if (column == 1) {
                if (server.isRunning()) {
                    item->setForeground(QColor(QStringLiteral("#3daa3d")));
                } else if (server.state == QLatin1String("crashed")) {
                    item->setForeground(QColor(QStringLiteral("#d9534f")));
                }
            }
            m_serverModel->setItem(row, column, item);
        }
    }

    if (!servers.isEmpty()) {
        ui->serverView->selectRow(0);
    }
}

void HyperMinePage::populateInstances()
{
    const QString previous = ui->instanceCombo->currentData().toString();

    ui->instanceCombo->clear();
    auto* instances = APPLICATION->instances();
    for (int i = 0; i < instances->count(); ++i) {
        auto* instance = instances->at(i);
        if (!instance) {
            continue;
        }
        ui->instanceCombo->addItem(instance->name(), instance->id());
    }

    const int index = ui->instanceCombo->findData(previous.isEmpty() ? APPLICATION->settings()->get(kLastInstanceKey).toString()
                                                                     : previous);
    if (index >= 0) {
        ui->instanceCombo->setCurrentIndex(index);
    }
    refreshPlayAddress();
}

std::optional<HyperMineServer> HyperMinePage::selectedServer() const
{
    const QModelIndexList selected = ui->serverView->selectionModel()->selectedRows();
    if (selected.isEmpty()) {
        return std::nullopt;
    }
    auto* first = m_serverModel->item(selected.first().row(), 0);
    if (!first) {
        return std::nullopt;
    }
    const QString id = first->data(Qt::UserRole).toString();
    for (const auto& server : m_servers) {
        if (server.id == id) {
            return server;
        }
    }
    return std::nullopt;
}

quint16 HyperMinePage::targetPort() const
{
    if (const auto server = selectedServer()) {
        return server->mcPort;
    }
    // Nothing selected: fall back to a remembered game port so Play still has a sensible
    // target rather than silently doing nothing. toInt() takes no default in Qt 6, and
    // yields 0 for an unset setting, so the fallback is applied here.
    const int stored = APPLICATION->settings()->get(kDefaultMcPortKey).toInt();
    return (stored > 0 && stored <= 65535) ? static_cast<quint16>(stored) : quint16{25565};
}

QUrl HyperMinePage::suggestedPanelUrl() const
{
    if (!m_tunnel->hasInterface()) {
        return {};
    }
    const QString host = m_tunnel->interface().host();
    if (host.isEmpty()) {
        return {};
    }
    const int configured = APPLICATION->settings()->get(kPanelPortKey).toInt();
    const int port = (configured > 0 && configured <= 65535) ? configured : kDefaultPanelPort;
    return QUrl(QStringLiteral("http://%1:%2").arg(host).arg(port));
}

void HyperMinePage::refreshTunnelLabels()
{
    const auto& iface = m_tunnel->interface();
    const auto& status = m_tunnel->status();

    if (!m_tunnel->hasInterface()) {
        ui->configLabel->setText(tr("No tunnel imported yet."));
        ui->tunnelLabel->setText(QStringLiteral("—"));
        ui->endpointLabel->setText(QStringLiteral("—"));
        ui->localLabel->setText(QStringLiteral("—"));
        ui->statusLabel->setText(tr("No tunnel"));
        ui->handshakeLabel->setText(QStringLiteral("—"));
        ui->listenLabel->setText(QStringLiteral("—"));
        ui->tunnelHintLabel->clear();
        refreshButtonStates();
        return;
    }

    ui->configLabel->setText(m_tunnel->confPath());
    ui->tunnelLabel->setText(QStringLiteral("%1  (%2)").arg(iface.name, iface.localHost()));

    // Prefer what wg reports over what the config says: after roaming, the config's
    // endpoint is stale and the live one is what the peer is actually reached at.
    const QString endpoint = status.endpoint.isEmpty() ? iface.peer.endpoint : status.endpoint;
    ui->endpointLabel->setText(endpoint.isEmpty() ? tr("(none — roaming)") : endpoint);

    ui->localLabel->setText(iface.localHost().isEmpty() ? QStringLiteral("-")
                                                       : QStringLiteral("%1 -> %2").arg(iface.localHost(), iface.host()));
    ui->listenLabel->setText(status.listenPort ? QString::number(status.listenPort) : QStringLiteral("-"));

    switch (status.state) {
    case WireGuardTunnel::State::Down:
        ui->statusLabel->setText(tr("Down"));
        break;
    case WireGuardTunnel::State::Starting:
        ui->statusLabel->setText(tr("Starting…"));
        break;
    case WireGuardTunnel::State::Up:
        ui->statusLabel->setText(m_tunnel->isHandshakeFresh() ? tr("Connected") : tr("Up, waiting for a handshake"));
        break;
    case WireGuardTunnel::State::Failed:
        ui->statusLabel->setText(tr("Failed"));
        break;
    }

    if (status.lastHandshake > 0) {
        const qint64 age = QDateTime::currentSecsSinceEpoch() - status.lastHandshake;
        QString when = QDateTime::fromSecsSinceEpoch(status.lastHandshake).toString(QStringLiteral("HH:mm:ss"));
        if (age < 0) {
            when = tr("%1 (clock skew — treat as unknown)").arg(when);
        } else if (age < 120) {
            when = tr("%1s ago").arg(age);
        }
        ui->handshakeLabel->setText(when);
    } else if (status.state == WireGuardTunnel::State::Up) {
        ui->handshakeLabel->setText(tr("none yet"));
    } else {
        ui->handshakeLabel->setText(QStringLiteral("—"));
    }

    ui->tunnelHintLabel->setText(status.error.isEmpty() ? WireGuardTunnel::controlToolHint() : status.error);
    refreshButtonStates();
}

void HyperMinePage::refreshButtonStates()
{
    const bool hasTunnel = m_tunnel->hasInterface();
    const bool up = m_tunnel->isUp();
    const bool starting = m_tunnel->state() == WireGuardTunnel::State::Starting;
    const bool canControl = WireGuardTunnel::controlToolAvailable();

    ui->upButton->setEnabled(hasTunnel && canControl && !up && !starting);
    ui->downButton->setEnabled(hasTunnel && canControl && (up || starting));
    ui->forgetButton->setEnabled(hasTunnel);

    const bool haveSelection = selectedServer().has_value();
    const bool panelOk = m_client->canSend() && !m_client->isBusy();
    ui->refreshButton->setEnabled(panelOk);
    ui->startButton->setEnabled(panelOk && haveSelection);
    ui->stopButton->setEnabled(panelOk && haveSelection);
}

void HyperMinePage::refreshPanelAvailability()
{
    // Whether the label is currently showing a "cannot reach the panel" reason. Tracked
    // explicitly rather than by matching the label's text, because the word "tunnel" in a
    // standalone lookup is a different translation unit from the same word inside a
    // sentence -- so a text match silently stops working in any non-English build.
    const QString reason = m_client->blockedReason();
    if (!reason.isEmpty()) {
        if (!m_panelBlocked) {
            m_panelBlocked = true;
            ui->panelStatusLabel->setText(reason);
        }
        return;
    }
    if (m_panelBlocked) {
        m_panelBlocked = false;
        ui->panelStatusLabel->setText(m_servers.isEmpty()
                                          ? QString()
                                          : tr("%n server(s) reported by the panel.", nullptr, m_servers.size()));
    }
}

void HyperMinePage::refreshPlayAddress()
{
    if (!m_tunnel->hasInterface()) {
        ui->playAddressLabel->setText(tr("Import a WireGuard configuration to play through the tunnel."));
        ui->playButton->setEnabled(false);
        return;
    }
    const QString address = m_tunnel->tunnelAddress(targetPort());
    if (address.isEmpty()) {
        ui->playAddressLabel->setText(tr("This configuration has no IPv4 peer address to connect to."));
        ui->playButton->setEnabled(false);
        return;
    }

    const bool ready = m_tunnel->isUp() && m_tunnel->isHandshakeFresh();
    ui->playAddressLabel->setText(
        ready ? tr("Will connect to %1").arg(address)
              : tr("Will connect to %1 once the tunnel has handshaked.").arg(address));
    ui->playButton->setEnabled(!ui->instanceCombo->currentData().toString().isEmpty());
}

void HyperMinePage::onPlayClicked()
{
    const QString instanceId = ui->instanceCombo->currentData().toString();
    if (instanceId.isEmpty()) {
        CustomMessageBox::selectable(this, tr("No instance to play with"),
                                      tr("Add an instance in the Instances tab first."))
            ->show();
        return;
    }
    if (!m_tunnel->hasInterface()) {
        CustomMessageBox::selectable(this, tr("No tunnel"),
                                      tr("Import a WireGuard configuration before playing through the tunnel."))
            ->show();
        return;
    }

    APPLICATION->settings()->set(kLastInstanceKey, instanceId);
    beginPlay(instanceId, m_tunnel->tunnelAddress(targetPort()));
}

void HyperMinePage::beginPlay(const QString& instanceId, const QString& address)
{
    if (address.isEmpty()) {
        CustomMessageBox::selectable(this, tr("No address to connect to"),
                                      tr("The tunnel configuration has no IPv4 peer address."))
            ->show();
        return;
    }

    m_pendingInstanceId = instanceId;
    m_pendingAddress = address;

    if (ui->autoTunnelCheck->isChecked() && !m_tunnel->isUp()) {
        appendLog(tr("Bringing the tunnel up before launching."));
        m_tunnel->bringUp();
    }

    // The timeout is driven by its own timer rather than by tunnel status changes. With
    // the tunnel down and "bring up first" unticked, no status change ever arrives, so a
    // signal-driven timeout would never be evaluated and the click would look inert.
    m_pendingPlayTimer->stop();
    m_pendingPlayTimer->start();
    tryCompletePendingPlay();
}

void HyperMinePage::tryCompletePendingPlay()
{
    if (m_pendingInstanceId.isEmpty() || m_pendingAddress.isEmpty()) {
        return;
    }

    if (!m_tunnel->isUp() || !m_tunnel->isHandshakeFresh()) {
        return;
    }

    auto* instance = APPLICATION->instances()->getInstanceById(m_pendingInstanceId);
    if (!instance) {
        clearPendingPlay();
        CustomMessageBox::selectable(this, tr("That instance is gone"),
                                      tr("The instance this was going to launch no longer exists."))
            ->show();
        return;
    }
    if (instance->isRunning()) {
        clearPendingPlay();
        CustomMessageBox::selectable(this, tr("That instance is already running"),
                                      tr("Stop '%1' before launching it again.").arg(instance->name()))
            ->show();
        return;
    }

    const QString address = m_pendingAddress;
    clearPendingPlay();

    // MinecraftTarget::parse with useWorld=false builds the "join this server on launch"
    // target, which is exactly what the --server command line option produces.
    auto target = std::make_shared<MinecraftTarget>(MinecraftTarget::parse(address, false));

    appendLog(tr("Launching %1 into %2").arg(instance->name(), address));
    APPLICATION->launch(instance, LaunchMode::Normal, target);
}

void HyperMinePage::clearPendingPlay()
{
    m_pendingPlayTimer->stop();
    m_pendingInstanceId.clear();
    m_pendingAddress.clear();
}

void HyperMinePage::onPendingPlayTimeout()
{
    if (m_pendingInstanceId.isEmpty()) {
        return;
    }
    const QString address = m_pendingAddress;

    // Work out why nothing happened, rather than assuming. A tunnel that is up but has
    // not handshaked is a real failure; a tunnel that never went up because the bring-up
    // itself failed is a different one; and a tunnel that is down because the user
    // unticked the auto-bring box is not a failure at all.
    if (m_tunnel->state() == WireGuardTunnel::State::Failed) {
        clearPendingPlay();
        CustomMessageBox::selectable(
            this, tr("The tunnel could not be brought up"),
            tr("Bringing the tunnel up failed, so %1 was not launched. %2")
                .arg(address, m_tunnel->status().error.isEmpty() ? tr("") : m_tunnel->status().error))
            ->show();
        return;
    }
    if (m_tunnel->isUp()) {
        clearPendingPlay();
        CustomMessageBox::selectable(
            this, tr("The tunnel never connected"),
            tr("The tunnel came up but never completed a handshake after %1 seconds, so %2 was not launched. Check "
               "that the endpoint is reachable and that the keys match the server.")
                .arg(kPlayHandshakeTimeoutMs / 1000)
                .arg(address))
            ->show();
        return;
    }
    if (!ui->autoTunnelCheck->isChecked()) {
        clearPendingPlay();
        CustomMessageBox::selectable(
            this, tr("The tunnel is not up"),
            tr("The tunnel is down and 'Bring the tunnel up first' is off, so %1 was not launched.")
                .arg(address))
            ->show();
        return;
    }
    // Auto-bring is on and the tunnel is still down without an error: the bring-up was
    // never asked for. Give up quietly rather than accusing the user of a choice they
    // did not make.
    clearPendingPlay();
}

void HyperMinePage::appendLog(const QString& line)
{
    const QString stamp = QTime::currentTime().toString(QStringLiteral("HH:mm:ss"));
    ui->logView->appendPlainText(QStringLiteral("[%1] %2").arg(stamp, line));
}
